In [ ]:
'''
熊毅
2016011467
'''

In [34]:
import tensorflow as tf

a = tf.reshape(tf.range(5*5),(5,5))
b = tf.reshape(tf.range(24,-1,-1),(5,5))

sess = tf.Session()


In [32]:
g1 = tf.get_default_graph()
max_mat = tf.where(a>b,a,b,name='where')
print(sess.run(max_mat))

[[24 23 22 21 20]
 [19 18 17 16 15]
 [14 13 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### tf.maximum
### tf.minimum

### tf.TensorArray

### 配合`tf.while_loop`使用

In [25]:
import tensorflow as tf
import random
ta = tf.TensorArray(dtype=tf.float32,dynamic_size=True,size=1)
time = tf.constant(0)

In [31]:
def cond(time,ta):
    return time<3
def body(time,ta):
    ta = ta.write(time,tf.random_normal([4],dtype=tf.float32))
    return time+1,ta
time,ta = tf.while_loop(cond,body,[time,ta])

In [27]:
sess = tf.Session()
result_tens = ta.stack()
print(sess.run(result_tens))

[[-0.608475    0.83108574 -0.39135402 -1.5966594 ]
 [-0.605666   -0.7972678  -0.87241834 -1.3459315 ]
 [ 0.08015171  0.9413354  -0.42477417  0.2996975 ]]
